@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidGVzdCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiMyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3RAbWFpbC5jb20iLCJleHAiOjE3MjYyNTY3NDgsImlzcyI6IlRvZG9Gb3JnZSIsImF1ZCI6IlRvZG9Gb3JnZSJ9.Rna_dP1gPr5CqkWitGx_8QTn8ti5tKSC5TXL6yP5msc
POST http://localhost:5127/api/boards
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "Title": "New Board!",
    "Description": "A board to manage my projects"
}